# ReadMe https://digitology.tech/docs/python_3/library/tutrle.html
import turtle as trl


#ToDo: узнать размер экрана
def draw_square(side_lnegth, side_lnegth2, side_lnegth3, side_lnegth4):
    trl.forward(850)
    trl.forward(-850)
    trl.left(60)
    trl.forward(550)
    trl.forward(-550)
    trl.left(60)
    trl.forward(550)
    trl.forward(-550)
    trl.left(60)
    trl.forward(850)
    trl.forward(-850)
    trl.left(60)
    trl.forward(550)
    trl.forward(-550)
    trl.left(60)
    trl.forward(550)
    trl.forward(-550)

    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(60)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(60)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(60)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(60)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(60)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(120)
    trl.forward(side_lnegth)
    trl.left(60)

    trl.forward(side_lnegth2)
    trl.left(120)
    trl.forward(side_lnegth2)
    trl.left(60)
    trl.forward(side_lnegth2)
    trl.left(60)
    trl.forward(side_lnegth2)
    trl.left(60)
    trl.forward(side_lnegth2)
    trl.left(60)
    trl.forward(side_lnegth2)
    trl.left(60)
    trl.forward(side_lnegth2)
    trl.left(60)

    trl.goto(0, 0)
    trl.left(240)

    trl.forward(side_lnegth3)
    trl.left(120)
    trl.forward(side_lnegth3)
    trl.left(60)
    trl.forward(side_lnegth3)
    trl.left(60)
    trl.forward(side_lnegth3)
    trl.left(60)
    trl.forward(side_lnegth3)
    trl.left(60)
    trl.forward(side_lnegth3)
    trl.left(60)
    trl.forward(side_lnegth3)
    trl.left(60)

    trl.goto(0, 0)
    trl.left(240)

    trl.forward(side_lnegth4)
    trl.left(120)
    trl.forward(side_lnegth4)
    trl.left(60)
    trl.forward(side_lnegth4)
    trl.left(60)
    trl.forward(side_lnegth4)
    trl.left(60)
    trl.forward(side_lnegth4)
    trl.left(60)
    trl.forward(side_lnegth4)
    trl.left(60)
    trl.forward(side_lnegth4)
    trl.left(60)

    trl.goto(0,0)
    trl.right(60)


# настройка
trl.goto(0, 0)
trl.shape("turtle")
trl.speed(5)
side_lnegth = 200
side_lnegth2 = 50
side_lnegth3 = 100
side_lnegth4 = 150
# рисование
draw_square(side_lnegth, side_lnegth2, side_lnegth3, side_lnegth4)

trl.done() 
